# NWPLux
# Haseeb ur Rehman
# Funded by the Fonds National de la Recherche Luxembourg (FNR),
# Industrial Fellowship, Project No. 17130773

"""
Build a LaTeX longtable manifest of every analysis script in the NWPLux-pipeline
repository, grouped by pipeline stage (top-level folder). For each script the
manifest lists its path and a one-line purpose taken from the script's own module
docstring / leading comment (falling back to a humanised filename).

Writes: script_manifest.tex  (\input from the thesis Supplementary Data appendix).
"""

import os
import re

REPO = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(REPO, "script_manifest.tex")

# Header lines we inject into every file – skip them when hunting for a description.
ATTRIB = ("NWPLux", "Haseeb ur Rehman", "Funded by", "Industrial Fellowship")

GROUP_TITLES = {
    "01_NWP_development": "NWP Model Development (Chapter~\\ref{ch:nwp})",
    "02_physics_vs_ai": "Physics vs.\\ AI Benchmark (Chapter~\\ref{ch:ai})",
    "03_flood_simulation": "Hydraulic Flood Simulation (Chapter~\\ref{ch:flood})",
    "bibliometric_analysis": "Bibliometric Analysis (Chapter~\\ref{ch:lit_review})",
}


def tex_escape(s):
    for a, b in [("\\", "\\textbackslash{}"), ("_", "\\_"), ("&", "\\&"),
                 ("%", "\\%"), ("#", "\\#"), ("{", "\\{"), ("}", "\\}"),
                 ("$", "\\$"), ("~", "\\textasciitilde{}"), ("^", "\\textasciicircum{}")]:
        s = s.replace(a, b)
    return s


def humanise(fn):
    base = os.path.splitext(fn)[0].replace("_", " ").strip()
    return base[:1].upper() + base[1:]


def describe(path, fn):
    """Return a short one-line purpose for the script."""
    try:
        with open(path, "r", errors="ignore") as f:
            text = f.read()
    except OSError:
        return humanise(fn)
    # Python module docstring
    m = re.search(r'"""(.*?)"""', text, re.S)
    if m:
        first = " ".join(m.group(1).strip().split())
        first = first.split(". ")[0]
        if first:
            return first[:160]
    # otherwise first meaningful comment line that is not the attribution header
    for line in text.splitlines():
        s = line.strip().lstrip("#").strip()
        if not s or s.startswith("!") or s.startswith("-*-"):
            continue
        if any(tag in s for tag in ATTRIB):
            continue
        if s.lower().startswith(("import ", "from ", "set ", "#!")):
            break
        return s[:160]
    return humanise(fn)


def collect():
    groups = {}
    for dirpath, dirnames, filenames in os.walk(REPO):
        if ".git" in dirpath.split(os.sep):
            continue
        for fn in sorted(filenames):
            if not (fn.endswith(".py") or fn.endswith(".sh")):
                continue
            if fn == os.path.basename(__file__):
                continue
            rel = os.path.relpath(os.path.join(dirpath, fn), REPO)
            top = rel.split(os.sep)[0]
            groups.setdefault(top, []).append((rel, describe(os.path.join(dirpath, fn), fn)))
    return groups


def main():
    groups = collect()
    order = ["01_NWP_development", "02_physics_vs_ai", "03_flood_simulation",
             "bibliometric_analysis"]
    order += [g for g in sorted(groups) if g not in order]

    total = sum(len(v) for v in groups.values())
    lines = []
    lines.append("% AUTO-GENERATED by generate_script_manifest.py -- do not hand-edit")
    lines.append("{\\footnotesize")
    lines.append("\\begin{longtable}{p{0.40\\textwidth} p{0.54\\textwidth}}")
    lines.append("\\caption{Manifest of the %d analysis scripts published in the "
                 "NWPLux-pipeline repository, grouped by pipeline stage. Each entry "
                 "gives the path within the repository and a one-line description.}"
                 "\\label{tab:script_manifest}\\\\" % total)
    lines.append("\\toprule\n\\textbf{Script (repository path)} & \\textbf{Purpose} \\\\\n\\midrule")
    lines.append("\\endfirsthead")
    lines.append("\\multicolumn{2}{c}{\\tablename\\ \\thetable{} -- continued}\\\\")
    lines.append("\\toprule\n\\textbf{Script (repository path)} & \\textbf{Purpose} \\\\\n\\midrule")
    lines.append("\\endhead")
    lines.append("\\midrule\\multicolumn{2}{r}{\\emph{continued on next page}}\\\\")
    lines.append("\\endfoot")
    lines.append("\\bottomrule\n\\endlastfoot")

    for g in order:
        if g not in groups:
            continue
        title = GROUP_TITLES.get(g, tex_escape(g))
        lines.append("\\multicolumn{2}{l}{\\textbf{%s}}\\\\\n\\midrule" % title)
        for rel, desc in groups[g]:
            lines.append("\\texttt{%s} & %s \\\\" % (tex_escape(rel), tex_escape(desc)))
        lines.append("\\midrule")

    lines.append("\\end{longtable}}")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("Wrote", OUT, "with", total, "scripts")


if __name__ == "__main__":
    main()
